### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by eshohet** [eshohet/Reddit-Cash#1]
- [ ] Perma link for each post 
- [ ] Add README.md
- [ ] Referral program
- [ ] Optimistic UI implementation
- [ ] Ability to sell a specific amount of a post
- [ ] Change favicon
- [ ] Implement cost / fee calculation
- [ ] Realtime functionality
